apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: gcr.io/$PROJECT_ID/kubia:v1
        ports:
        - containerPort: 8080
          protocol: TCP
