apiVersion: v1
kind: Pod
metadata:
  name: kubia-v2
  labels:
      creation_method: manual
      env: prod
spec:
  containers:
  - image: gcr.io/$PROJECT_ID/kubia:v1
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
